module.exports = {
  colors: {
    col1: "white",
    text1: "red",
    text2: "grey",
    text3: "black",
  },
  titles: {
    title1: 30,
    btntxt: 20,
  },
  btn1: {
    width: 150,
    height: 50,
    backgroundColor: "#0ac1d1",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    color: "white",
  },
  btn2: {
    width: 150,
    height: 50,
    backgroundColor: "#0ac1d1",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    color: "white",
  },
  hr80: {
    width: "80%",
    // borderBottomColor: '#E0E0E0',
    borderBottomColor: "#0ac1d1",
    borderBottomWidth: 1,
    marginVertical: 20,
  },
  veg: {
    backgroundColor: "green",
    width: 20,
    height: 20,
    borderRadius: 5,
  },
  nonveg: {
    backgroundColor: "red",
    width: 20,
    height: 20,
    borderRadius: 5,
  },

  incdecbtn:{
    backgroundColor:'red',
    alignItems:'center',
    justifyContent:'center',
    borderRadius:50,
    elevation:10,
    padding:10,
    color:'white',
    fontSize:20,
    fontWeight:'bold',
  },

  indecinput:{
    backgroundColor:'white',
    alignItems:'center',
    justifyContent:'center',
    elevation:10,
    padding:10,
    width:50,
    marginHorizontal:10,
    fontSize:20,
  },
  
  indecout:{
    flexDirection:'row',
    alignItems:'center',
    margin:10,
  },
};
